<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Leave Balance Report - {{ $user->name }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; }
        .header { text-align: center; margin-bottom: 20px; }
        .title { font-size: 19px; font-weight: bold; }
        .subtitle { font-size: 14px; color: #666; }
        .employee-info { margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
        .text-right { text-align: right; }
        .footer { margin-top: 30px; font-size: 10px; text-align: right; color: #666; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Leave Balance Report</div>
        <div class="subtitle">Generated on {{ $generated_at }}</div>
    </div>

    <div class="employee-info">
        <p><strong>Employee:</strong> {{ $user->name }}</p>
        <p><strong>Department:</strong> {{ $user->department->name ?? 'N/A' }}</p>
        <p><strong>Employee ID:</strong> {{ $user->employee_id ?? 'N/A' }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Leave Type</th>
                <th class="text-right">Entitled</th>
                <th class="text-right">Used</th>
                <th class="text-right">Pending</th>
                <th class="text-right">Available</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($summaries as $summary)
                <tr>
                    <td>{{ $summary['leaveType']->name }}</td>
                    <td class="text-right">{{ number_format($summary['entitled'], 1) }}</td>
                    <td class="text-right">{{ number_format($summary['taken'], 1) }}</td>
                    <td class="text-right">{{ number_format($summary['requested'] + $summary['planned'], 1) }}</td>
                    <td class="text-right">{{ number_format($summary['available_actual'], 1) }}</td>
                </tr>
            @endforeach
            <tr style="font-weight: bold;">
                <td>Total</td>
                <td class="text-right">{{ number_format(collect($summaries)->sum('entitled'), 1) }}</td>
                <td class="text-right">{{ number_format(collect($summaries)->sum('taken'), 1) }}</td>
                <td class="text-right">{{ number_format(collect($summaries)->sum(function($item) { 
                    return $item['requested'] + $item['planned']; 
                }), 1) }}</td>
                <td class="text-right">{{ number_format(collect($summaries)->sum('available_actual'), 1) }}</td>
            </tr>
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by {{ Auth::user()->name }}</p>
    </div>
</body>
</html>